my-shop/myshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.http import HttpResponse
from cms.sitemaps import CMSSitemap
from myshop.sitemap import ProductSitemap

sitemaps = {'cmspages': CMSSitemap,
            'products': ProductSitemap}


def render_robots(request):
    permission = 'noindex' in settings.ROBOTS_META_TAGS and 'Disallow' or 'Allow'
    return HttpResponse('User-Agent: *\n%s: /\n' % permission, content_type='text/plain')


i18n_urls = (
    url(r'^admin/', admin.site.urls),
    url(r'^', include('cms.urls')),
)
urlpatterns = [
    url(r'^robots\.txt$', render_robots),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps}, name='sitemap'),
    url(r'^shop/', include('shop.urls')),
]
if settings.USE_I18N:
    urlpatterns.extend(i18n_patterns(*i18n_urls))
else:
    urlpatterns.extend(i18n_urls)
urlpatterns.extend(
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

my-shop/myshop/models.py
from decimal import Decimal
from django.core.validators import MinValueValidator
from django.db import models
from django.utils.translation import ugettext_lazy as _
from djangocms_text_ckeditor.fields import HTMLField
from cms.models.fields import PlaceholderField
from shop.money import Money, MoneyMaker
from shop.money.fields import MoneyField
from shop.models.product import BaseProduct, BaseProductManager, AvailableProductMixin, CMSPageReferenceMixin
from shop.models.defaults.cart import Cart
from shop.models.defaults.cart_item import CartItem
from shop.models.defaults.order_item import OrderItem
from shop.models.defaults.order import Order
from shop.models.defaults.mapping import ProductPage, ProductImage
from shop.models.defaults.address import BillingAddress, ShippingAddress
from shop.models.defaults.customer import Customer


__all__ = ['Cart', 'CartItem', 'Order', 'OrderItem',
           'BillingAddress', 'ShippingAddress', 'Customer', ]


class Manufacturer(models.Model):
    name = models.CharField(
        _("Name"),
        max_length=50,
        unique=True,
    )

    def __str__(self):
        return self.name


class ProductManager(BaseProductManager):
    pass


class Product(CMSPageReferenceMixin, BaseProduct):
    """
    Base class to describe a polymorphic product. Here we declare common fields available in all of
    our different product types. These common fields are also used to build up the view displaying
    a list of all products.
    """
    product_name = models.CharField(
        _("Product Name"),
        max_length=255,
    )

    slug = models.SlugField(
        _("Slug"),
        unique=True,
    )

    caption = HTMLField(
        verbose_name=_("Caption"),
        blank=True,
        null=True,
        configuration='CKEDITOR_SETTINGS_CAPTION',
        help_text=_(
            "Short description used in the catalog's list view of products."),
    )

    # common product properties
    manufacturer = models.ForeignKey(
        Manufacturer,
        on_delete=models.CASCADE,
        verbose_name=_("Manufacturer"),
    )

    # controlling the catalog
    order = models.PositiveIntegerField(
        _("Sort by"),
        db_index=True,
    )

    cms_pages = models.ManyToManyField(
        'cms.Page',
        through=ProductPage,
        help_text=_("Choose list view this product shall appear on."),
    )

    images = models.ManyToManyField(
        'filer.Image',
        through=ProductImage,
    )

    class Meta:
        ordering = ('order',)
        verbose_name = _("Product")
        verbose_name_plural = _("Products")

    objects = ProductManager()

    # filter expression used to lookup for a product item using the Select2 widget
    lookup_fields = ['product_name__icontains']

    def __str__(self):
        return self.product_name

    @property
    def sample_image(self):
        return self.images.first()


class Commodity(AvailableProductMixin, Product):
    """
    This Commodity model inherits from polymorphic Product, and therefore has to be redefined.
    """
    unit_price = MoneyField(
        _("Unit price"),
        decimal_places=3,
        help_text=_("Net price for this product"),
    )

    product_code = models.CharField(
        _("Product code"),
        max_length=255,
        unique=True,
    )

    quantity = models.PositiveIntegerField(
        _("Quantity"),
        default=0,
        validators=[MinValueValidator(0)],
        help_text=_("Available quantity in stock")
    )

    # controlling the catalog
    placeholder = PlaceholderField("Commodity Details")
    show_breadcrumb = True  # hard coded to always show the product's breadcrumb

    class Meta:
        verbose_name = _("Commodity")
        verbose_name_plural = _("Commodities")

    default_manager = ProductManager()

    def get_price(self, request):
        return self.unit_price


class SmartCard(AvailableProductMixin, Product):
    unit_price = MoneyField(
        _("Unit price"),
        decimal_places=3,
        help_text=_("Net price for this product"),
    )

    card_type = models.CharField(
        _("Card Type"),
        choices=[2 * ('{}{}'.format(s, t),)
                 for t in ['SD', 'SDXC', 'SDHC', 'SDHC II'] for s in ['', 'micro ']],
        max_length=15,
    )

    speed = models.CharField(
        _("Transfer Speed"),
        choices=[(str(s), "{} MB/s".format(s))
                 for s in [4, 20, 30, 40, 48, 80, 95, 280]],
        max_length=8,
    )

    product_code = models.CharField(
        _("Product code"),
        max_length=255,
        unique=True,
    )

    storage = models.PositiveIntegerField(
        _("Storage Capacity"),
        help_text=_("Storage capacity in GB"),
    )

    description = HTMLField(
        _("Description"),
        configuration='CKEDITOR_SETTINGS_DESCRIPTION',
        help_text=_("Long description for the detail view of this product."),
    )

    quantity = models.PositiveIntegerField(
        _("Quantity"),
        default=0,
        validators=[MinValueValidator(0)],
        help_text=_("Available quantity in stock")
    )

    class Meta:
        verbose_name = _("Smart Card")
        verbose_name_plural = _("Smart Cards")
        ordering = ['order']

    # filter expression used to lookup for a product item using the Select2 widget
    lookup_fields = ['product_code__startswith', 'product_name__icontains']

    def get_price(self, request):
        return self.unit_price

    default_manager = ProductManager()


class OperatingSystem(models.Model):
    name = models.CharField(
        _("Name"),
        max_length=50,
        unique=True,
    )

    def __str__(self):
        return self.name


class SmartPhoneModel(Product):
    """
    A generic smart phone model, which must be concretized by a `SmartPhoneVariant` - see below.
    """
    BATTERY_TYPES = [
        (1, "Lithium Polymer (Li-Poly)"),
        (2, "Lithium Ion (Li-Ion)"),
    ]
    WIFI_CONNECTIVITY = [
        (1, "802.11 b/g/n"),
    ]
    BLUETOOTH_CONNECTIVITY = [
        (1, "Bluetooth 4.0"),
        (2, "Bluetooth 3.0"),
        (3, "Bluetooth 2.1"),
    ]
    battery_type = models.PositiveSmallIntegerField(
        _("Battery type"),
        choices=BATTERY_TYPES,
    )

    battery_capacity = models.PositiveIntegerField(
        _("Capacity"),
        help_text=_("Battery capacity in mAh"),
    )

    ram_storage = models.PositiveIntegerField(
        _("RAM"),
        help_text=_("RAM storage in MB"),
    )

    wifi_connectivity = models.PositiveIntegerField(
        _("WiFi"),
        choices=WIFI_CONNECTIVITY,
        help_text=_("WiFi Connectivity"),
    )

    bluetooth = models.PositiveIntegerField(
        _("Bluetooth"),
        choices=BLUETOOTH_CONNECTIVITY,
        help_text=_("Bluetooth Connectivity"),
    )

    gps = models.BooleanField(
        _("GPS"),
        default=False,
        help_text=_("GPS integrated"),
    )

    operating_system = models.ForeignKey(
        OperatingSystem,
        on_delete=models.CASCADE,
        verbose_name=_("Operating System"),
    )

    width = models.DecimalField(
        _("Width"),
        max_digits=4,
        decimal_places=1,
        help_text=_("Width in mm"),
    )

    height = models.DecimalField(
        _("Height"),
        max_digits=4,
        decimal_places=1,
        help_text=_("Height in mm"),
    )

    weight = models.DecimalField(
        _("Weight"),
        max_digits=5,
        decimal_places=1,
        help_text=_("Weight in gram"),
    )

    screen_size = models.DecimalField(
        _("Screen size"),
        max_digits=4,
        decimal_places=2,
        help_text=_("Diagonal screen size in inch"),
    )

    description = HTMLField(
        verbose_name=_("Description"),
        configuration='CKEDITOR_SETTINGS_DESCRIPTION',
        help_text=_(
            "Full description used in the catalog's detail view of Smart Phones."),
    )

    class Meta:
        verbose_name = _("Smart Phone")
        verbose_name_plural = _("Smart Phones")

    default_manager = ProductManager()

    def get_price(self, request):
        """
        Return the starting price for instances of this smart phone model.
        """
        if not hasattr(self, '_price'):
            if self.variants.exists():
                currency = self.variants.first().unit_price.currency
                aggr = self.variants.aggregate(models.Min('unit_price'))
                self._price = MoneyMaker(currency)(aggr['unit_price__min'])
            else:
                self._price = Money()
        return self._price

    def get_availability(self, request, **kwargs):
        variant = self.get_product_variant(**kwargs)
        return variant.get_availability(request)

    def deduct_from_stock(self, quantity, **kwargs):
        variant = self.get_product_variant(**kwargs)
        variant.deduct_from_stock(quantity)

    def is_in_cart(self, cart, watched=False, **kwargs):
        try:
            product_code = kwargs['product_code']
        except KeyError:
            return
        cart_item_qs = CartItem.objects.filter(cart=cart, product=self)
        for cart_item in cart_item_qs:
            if cart_item.product_code == product_code:
                return cart_item

    def get_product_variant(self, **kwargs):
        try:
            product_code = kwargs.get('product_code')
            return self.variants.get(product_code=product_code)
        except SmartPhoneVariant.DoesNotExist as e:
            raise SmartPhoneModel.DoesNotExist(e)

    def get_product_variants(self):
        return self.variants.all()


class SmartPhoneVariant(AvailableProductMixin, models.Model):
    product = models.ForeignKey(
        SmartPhoneModel,
        on_delete=models.CASCADE,
        verbose_name=_("Smartphone Model"),
        related_name='variants',
    )

    product_code = models.CharField(
        _("Product code"),
        max_length=255,
        unique=True,
    )

    unit_price = MoneyField(

my-shop/myshop/forms.py
from shop.forms.checkout import CustomerForm as CustomerFormBase


class CustomerForm(CustomerFormBase):
    field_order = ['salutation', 'first_name', 'last_name', 'email']

my-shop/myshop/templates/myshop/catalog/commodity-add2cart.html
{% extends "shop/catalog/available-product-add2cart.html" %}
{% load i18n %}

{% block available-quantity-in-stock %}{# intentionally empty #}{% endblock %}

{% block change-purchasing-quantity %}
<div class="d-flex flex-column w-25" ng-hide="context.availability.quantity">
	<div class="lead mt-1">
		{% trans "This item has already been sold" %}
	</div>
</div>
{% endblock %}

my-shop/myshop/templates/myshop/catalog/commodity-detail.html
{% extends "myshop/pages/default.html" %}
{% load cms_tags sekizai_tags sass_tags %}

{% block title %}{{ product.product_name }}{% endblock %}

{% block breadcrumb %}{% with extra_ance=product.product_name %}
	{% if product.show_breadcrumb %}{% include "shop/breadcrumb/default.html" %}{% endif %}
{% endwith %}{% endblock %}

{% block main-content %}
	{# the first `render_placeholder` is only required for editing the page #}
	{% render_placeholder product.placeholder %}{% render_placeholder product.placeholder as product_details %}
	{% if not product_details %}
<div class="container">
	<div class="row">
		<div class="col">
			<h1>{% render_model product "product_name" %}</h1>
			<p class="lead">Edit this page, then switch into <em>Structure</em> mode and add plugins to placeholder <code> {{ product.placeholder.slot }} </code>.</p>
		</div>
	</div>
</div>
	{% endif %}
{% endblock main-content %}

my-shop/myshop/templates/myshop/catalog/manufacturer-filter.html
{% load static sekizai_tags %}

{% addtoblock "js" %}<script src="{% static 'shop/js/filter-form.js' %}" type="text/javascript"></script>{% endaddtoblock %}
{% add_data "ng-requires" "django.shop.filter" %}

<form shop-product-filter="manufacturer" style="margin-bottom: 10px;">
	{{ filter.filter_set.form.as_div }}
</form>

my-shop/myshop/templates/myshop/catalog/product-detail.html
{% extends "myshop/pages/default.html" %}
{% load cms_tags sekizai_tags sass_tags %}

{% block title %}{{ product.product_name }}{% endblock %}

{% block breadcrumb %}{% with extra_ance=product.product_name %}
	{% include "shop/breadcrumb/default.html" %}
{% endwith %}{% endblock %}

{% block main-content %}
<div class="container">
	<div class="row">
		<div class="col">
			<h1>{% render_model product "product_name" %}</h1>
			{# the first `render_placeholder` is only required for editing the page #}
			{% render_placeholder product.placeholder %}{% render_placeholder product.placeholder as product_details %}
			{% if not product_details %}
			<p class="lead">Edit this page, then switch into <em>Structure</em> mode and add plugins to placeholder <code> {{ product.placeholder.slot }} </code>.</p>
			{% endif %}
		</div>
	</div>
</div>
{% endblock main-content %}

my-shop/myshop/templates/myshop/catalog/smartcard-detail.html
{% extends "myshop/catalog/product-detail.html" %}
{% load i18n cms_tags thumbnail %}

{% block main-content %}
{% thumbnail product.images.first 250x250 crop as thumb %}
<div class="container">
	<div class="row">
		<div class="col col-md-10 offset-md-1">
			<h1>{% render_model product "product_name" %}</h1>
			<div class="media mb-3 flex-column flex-md-row">
				<img class="mr-3 mb-3" src="{{ thumb.url }}" width="{{ thumb.width }}" height="{{ thumb.height }}" alt="{{ product.product_name }}">
				<div class="media-body">
					{{ product.description|safe }}
				</div>
			</div>
			<h4>{% trans "Details" %}</h4>
			<ul class="list-group mb-3">
				<li class="list-group-item d-flex">
					<div class="w-50">{% trans "Card Type" %}:</div>
					<strong>{{ product.get_card_type_display }}</strong>
				</li>
				<li class="list-group-item d-flex">
					<div class="w-50">{% trans "Storage capacity" %}:</div>
					<strong>{{ product.storage }} GB</strong>
				</li>
				<li class="list-group-item d-flex">
					<div class="w-50">{% trans "Manufacturer" %}:</div>
					<strong>{{ product.manufacturer }}</strong>
				</li>
			</ul>
			<!-- include "Add to Cart" dialog box -->
			{% include "shop/catalog/available-product-add2cart.html" with card_css_classes="mb-3" %}
		</div>
	</div>
</div>
{% endblock main-content %}

my-shop/myshop/templates/myshop/catalog/smartphone-add2cart.html
{% extends "shop/catalog/available-product-add2cart.html" %}
{% load i18n %}

{% block add-to-cart-url %}{{ product.get_absolute_url }}/add-smartphone-to-cart{% endblock %}

{% block available-quantity-in-stock %}
<div class="d-flex flex-column">
	<label for="product_code">{% trans "Internal Storage" %}</label>
	<select class="form-control" name="product_code" ng-model="context.product_code" ng-change="updateContext()" >
	{% for smartphone in product.variants.all %}
		<option value="{{ smartphone.product_code }}">
		{% if smartphone.storage == 0 %}{% trans "Pluggable" %}{% else %}{{ smartphone.storage }} GB{% endif %}
		</option>
	{% endfor %}
	</select>
</div>
	{{ block.super }}
{% endblock %}

my-shop/myshop/templates/myshop/catalog/smartphonemodel-detail.html
{% extends "myshop/catalog/product-detail.html" %}
{% load i18n static cms_tags sekizai_tags sass_tags %}

{% block main-content %}

{% addtoblock "css" %}<link href="{% sass_src 'shop/css/bsp-scrollpanel.scss' %}" rel="stylesheet" type="text/css" />{% endaddtoblock %}

{% addtoblock "js" %}<script src="{% static 'node_modules/angular-bootstrap-plus/src/scrollpanel/scrollpanel.js' %}" type="text/javascript"></script>{% endaddtoblock %}
{% add_data "ng-requires" "bs-plus.scrollpanel" %}

<div class="container">
	<div class="row">
		<div class="col col-md-10 offset-md-1">
			<h1>{% render_model product "product_name" %}</h1>
			<bsp-scrollpanel class="shop-product-detail">
				<ul>{% for img in product.images.all %}
					<li><img src="{{ img.url }}" alt="{{ product.product_name }}" /></li>
				{% endfor %}</ul>
			</bsp-scrollpanel>
		</div>
		<div class="col col-md-10 offset-md-1">
			<h4>{% trans "Details" %}</h4>
			{{ product.description|safe }}
			<ul class="list-group mb-3">
				<li class="list-group-item d-flex">
					<div class="w-50">{% trans "Manufacturer" %}:</div>
					<strong>{{ product.manufacturer }}</strong>
				</li>
				<li class="list-group-item d-flex">
					<div class="w-50">{% trans "Battery" %}:</div>
					<strong>{{ product.get_battery_type_display }} ({{ product.battery_capacity }} mAh)</strong>
				</li>
				<li class="list-group-item d-flex">
					<div class="w-50">{% trans "RAM Storage" %}:</div>
					<strong>{{ product.ram_storage }} MB</strong>
				</li>
				<li class="list-group-item d-flex">
					<div class="w-50">{% trans "WiFi Connectivity" %}:</div>
					<strong>{{ product.wifi_connectivity }}</strong>
				</li>
				<li class="list-group-item d-flex">
					<div class="w-50">Bluetooth:</div>
					<strong>{{ product.get_bluetooth_display }}</strong>
				</li>
				<li class="list-group-item d-flex">
					<div class="w-50">GPS:</div>
					<strong><i class="fa {{ product.gps|yesno:'fa-check,fa-times' }}"></i></strong>
				</li>
				<li class="list-group-item d-flex">
					<div class="w-50">{% trans "Dimensions" %}:</div>
					<strong>{{ product.width }} mm (w) &times; {{ product.height }} mm (h)</strong>
				</li>
				<li class="list-group-item d-flex">
					<div class="w-50">{% trans "Weight" %}:</div>
					<strong>{{ product.weight }} g</strong>
				</li>
				<li class="list-group-item d-flex">
					<div class="w-50">{% trans "Screen size" %}:</div>
					<strong>{{ product.screen_size }} ({% trans "inch" %})</strong>
				</li>
			</ul>

			<!-- include "Add to Cart" dialog box -->
			{% include "myshop/catalog/smartphone-add2cart.html" with use_modal_dialog=True card_css_classes="mb-3" %}
		</div>
	</div>
</div>

{% include "shop/catalog/bsp-scrollpanel.tmpl.html" %}

{% endblock main-content %}